### ISSUE TITLE
N_s is not working for me (issue from Reddit)

### ISSUE THREAD

**Issue by sabdemo** [kontheocharis/notion_scheduler#4]
I have: macOS Mojave, python 3.8, pip installed, Safari Browser.

What did I do in Notion:
1. I created a /page with a /table inside. 
2. I created the fields as it described in the instruction (title (text), recurrence (text), not on (text), start date (date), etc.)
3. I field the first line of the table with an example (Call Mom & Dad. Every Sunday at 11:00 until 21 December 2020, etc.)

When I turn a table as a calendar, I have a date at 14 September (as a start date in example), but not on any Sunday.

What did I do with Notion_scheduler:
1. Well, I installed it and since `notion_scheduler -h` returns the following in Terminal I guess it is installed correctly:

```
usage: notion_scheduler [-h] [--dry-run]
                        [--log-level {LogLevel.NORMAL,LogLevel.VERBOSE,LogLevel.QUIET}]
                        [--config-filename CONFIG_FILENAME]
                        [--delete-rescheduled] [--append]

optional arguments:
  -h, --help            show this help message and exit
  --dry-run             don't modify anything, just show what would be done
  --log-level {LogLevel.NORMAL,LogLevel.VERBOSE,LogLevel.QUIET}
                        the logging verbosity level to use
  --config-filename CONFIG_FILENAME
                        the config file to use (default is
                        $HOME/.config/notion_scheduler/config.yml, '-' for
                        stdin)
  --delete-rescheduled  also delete 'Rescheduled' events
  --append              only append events, do not delete existing 'Scheduled'
```

- I created a config.yml in Sublime text builder.
- <img width="1241" alt="1" src="https://user-images.githubusercontent.com/58350005/93665282-e9e24e80-fa7d-11ea-8b6d-467e8bdbe0cd.png">
-  For `tasks_collection_url: https://www.notion.so/XXXX` and `scheduled_collection_url: https://www.notion.so/XXXX` I copied XXXX from browser’s dress bar from the page where is the table. And `token_v2: XXXX` I took from developer tools panel. 
- I created manually a directory `~/.config/notion_scheduler` (I didn’t have this folder in `~/.config` directory) and copied there the config.yml.
- Now if I try `notion_scheduler --dry-run` I get this:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/notion_scheduler", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 121, in main
    run_scheduler(settings, config)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 237, in run_scheduler
    for row in todo_col.get_rows(filter=scheduled_filter)):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/basic.py", line 168, in get_rows
    return self.query(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/basic.py", line 165, in query
    return CollectionQuery(self, self._get_a_collection_view(), **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/query.py", line 38, in __init__
    self.filter = _normalize_query_data(filter, collection)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 33, in _normalize_query_data
    data[key] = _normalize_query_data(data[key], collection, recursive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 19, in _normalize_query_data
    return [
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 20, in <listcomp>
    _normalize_query_data(item, collection, recursive=True) for item in data
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 26, in _normalize_query_data
    data["property"] = _normalize_prop_name(data["property"], collection)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 11, in _normalize_prop_name
    return collection.get_schema_property(prop_name).get("id", "")
AttributeError: 'NoneType' object has no attribute 'get'
```
But as I wrote, I still don't have a proper event in the table calender.

**Comment by kontheocharis** [comment]
You need to ensure that the tables for `tasks_collection_url` and `scheduled_collection_url` are different. Furthermore, all the fields defined in `properties_to_sync` need to exist as columns in `tasks_collection_url`, as well as `scheduled_collection_url`. Finally, you need to define "Date field" in the scheduled table to be equal to the name of the column for which you want the date to appear in the tasks table.

**Comment by kontheocharis** [comment]
Your tasks will be generated in the table defined by `tasks_collection_url`. Basically, the table at `scheduled_collection_url` is only there to define the tasks that you want to be recurring, and the program reads them and adds them to the tasks table (`tasks_collection_url`).

**Comment by kontheocharis** [comment]
I will add some more descriptive documentation in the README soon.

**Comment by sabdemo** [comment]
Well, I have questions.

1. There are 'Title', 'Tags', and 'Priority' fields defined in `property_to_sync` but there are no such fields on your screenshots. Are this fields hide? If so, what should be in this fields? Well, Title I suppose is the text of the task itself, but Tags and Priority?
2. I am afraid, I didn't understand about "Date field". You have there "do on" and "due" and I don't understand what to do with this... 

It is not a problem at all, I will wait till the Readme update. But please describe this things a little bit more. Thank you!

**Comment by kontheocharis** [comment]
I have hidden those fields from the screenshots because they are not necessary. You can put whatever column names you want in `properties_to_sync`. Title, Tags and Priority are just an example, and they are just arbitrary columns that I happen to use in my tasks database. But yes, they have to be present in *both* databases for it to work. (And yes, Title means the name of the task.)

The Date field specifies the name of the date column in your tasks database, so the program knows where to put the date for each task. For example, I have two date columns "Do on" and "Due" in my tasks database, so in my scheduled database I can pick either one to put in the "Date field" and the date generated in the tasks database will appear accordingly.

**Comment by sabdemo** [comment]
Well, sorry, probably it is because I am not native english speaker and not a python user, but I will ask you further details. 
So: 

1. I created two tables, copied all the fields names.
<img width="1402" alt="Снимок экрана 2020-09-22 в 13 54 46" src="https://user-images.githubusercontent.com/58350005/93874070-789fd700-fcdb-11ea-99ca-47c04bee7081.png">
And did the same in the config.yml.
<img width="910" alt="Снимок экрана 2020-09-22 в 13 57 32" src="https://user-images.githubusercontent.com/58350005/93874135-953c0f00-fcdb-11ea-86f9-2afb14d275dc.png">

Does it looks like correctly now?


2. The scheduled database has 2 views, as I understand - the default view and the calendar view. The XXXX url for the `scheduled_collection_url` should be which view from? 

3. Date field. So, you have "Do on" and "Due". But the name of the date field of your Tasks database is "Start date". I don't understand what these do on and due should be related to.

4. Besides, you have the first and the last tasks "Call Mom & Dad" and "Competitive Programming Weekly Contest" both every Sunday and the first is "Do on" and the second is "Due". But in the output table they both appear the same way. What is the difference? What does it influence on?

5. After every changes in config.yml should I write any command in terminal or I should just update browser page with notion?

**Comment by kontheocharis** [comment]
1. No. The properties to sync should not be each property in the Scheduled database. To start, try just putting ["Name"]. The Tasks database (your Output) should only have the fields "Name", "Do on".
2. It doesn't matter.
3. No, that is the name on the Scheduled database. In my tasks database, I have two date fields, one named "Do on" and the other named "Due". The "Date field" property in the Scheduled database tells notion_scheduler whether to put the task date on the "Do on" field or the "Due" field in the Tasks database.
3. To run the program run `notion_scheduler --log-level=verbose`.

**Comment by sabdemo** [comment]
Maybe you could create a template page in Notion, which I could add to my Notion? Because I definitely don't get it... Well, now after `notion_scheduler --log-level=verbose` and page refresh I get automatically a filed Date in my Tasks database. But nothing more.

1. `tasks_collection_url` relates to Tasks database (my former Output). And `scheduled_collection_url` relates to Scheduled database (former Input). Right?

<img width="1349" alt="Снимок экрана 2020-09-26 в 2 21 15" src="https://user-images.githubusercontent.com/58350005/94323558-fb0bed80-ff9e-11ea-9231-8f66a4ce1f34.png">

2. "Do on" field should be a Select field in Tasks database?
3. Config.yml should I leave just so?

<img width="338" alt="Снимок экрана 2020-09-26 в 2 22 50" src="https://user-images.githubusercontent.com/58350005/94323647-4c1be180-ff9f-11ea-898a-dc6c5a981824.png">

4. Can you explain more the difference between Do on and Due? Again, your tasks "Call Mom & Dad" and "Competitive Programming Weekly Contest" are Do on and Due, but in the table they are identical... 

5. Maybe there is something wrong in my log after `notion_scheduler --log-level=verbose`? Here it is:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/notion_scheduler", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 121, in main
    run_scheduler(settings, config)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 237, in run_scheduler
    for row in todo_col.get_rows(filter=scheduled_filter)):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/basic.py", line 168, in get_rows
    return self.query(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/basic.py", line 165, in query
    return CollectionQuery(self, self._get_a_collection_view(), **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/query.py", line 38, in __init__
    self.filter = _normalize_query_data(filter, collection)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 33, in _normalize_query_data
    data[key] = _normalize_query_data(data[key], collection, recursive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 19, in _normalize_query_data
    return [
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 20, in <listcomp>
    _normalize_query_data(item, collection, recursive=True) for item in data
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 26, in _normalize_query_data
    data["property"] = _normalize_prop_name(data["property"], collection)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion/block/collection/common.py", line 11, in _normalize_prop_name
    return collection.get_schema_property(prop_name).get("id", "")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by kontheocharis** [comment]
1) yes.

"Do on" should be a type date. Remove the "Date" field. As for 4) you're wrong, they are not identical, they just appear that way because the screenshot is on a calendar view. Both "Due" and "Do on" fields are enabled in the screenshot. But each task there only has one or the other.

If you change the type of "Do on" to date on your Tasks database, that error will disappear.

I just want to make it clear, this is not some tool intended for end users, this is just something I created some time for my own use, that I thought could be useful for other people to build upon as well.

**Comment by sabdemo** [comment]
Yes, of course, I understand it was for your own use, but I really want to make it work for me, cause the solution is very great from my point of view and I doubt there will be any similar solution any soon. So I really hope you will manage to explain me what I am doing wrong... at any time you will be able to.

So I have now the following picture...

<img width="1359" alt="Снимок экрана 2020-09-26 в 14 50 51" src="https://user-images.githubusercontent.com/58350005/94340126-f7608100-0007-11eb-9db4-a4bcec294739.png">
<img width="1319" alt="Снимок экрана 2020-09-26 в 14 51 05" src="https://user-images.githubusercontent.com/58350005/94340136-fdeef880-0007-11eb-91e5-6dc597c082f0.png">
<img width="1253" alt="Снимок экрана 2020-09-26 в 14 51 21" src="https://user-images.githubusercontent.com/58350005/94340141-00e9e900-0008-11eb-893b-154894cd90e3.png">

I did `notion_scheduler --log-level=verbose`, I updated the page... Nothing happens((

**Comment by kontheocharis** [comment]
Okay, try to create a multi-select property in Tasks called "Tags" and another select in Tasks called "Status". Also create multi-select "Tags" in the Scheduled database. And try to run again. What's the output of the command when you run it?

**Comment by sabdemo** [comment]
```
INFO: Added row 'Call Mom' for 2020-09-20
INFO: Added row 'Call Mom' for 2020-09-27
INFO: Added row 'Call Mom' for 2020-10-04
INFO: Added row 'Call Mom' for 2020-10-11
INFO: Added row 'Call Mom' for 2020-10-18
INFO: Added row 'Call Mom' for 2020-10-25
INFO: Added row 'Call Mom' for 2020-11-01
INFO: Added row 'Call Mom' for 2020-11-08
INFO: Added row 'Call Mom' for 2020-11-15
INFO: Added row 'Call Mom' for 2020-11-22
INFO: Added row 'Call Mom' for 2020-11-29
INFO: Added row 'Call Mom' for 2020-12-06
INFO: Added row 'Call Mom' for 2020-12-13
INFO: Added row 'Call Mom' for 2020-12-20
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/notion_scheduler", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 121, in main
    run_scheduler(settings, config)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 247, in run_scheduler
    for entry in create_entries(settings, config, row):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notion_scheduler/main.py", line 156, in create_entries
    rr = rrule.rrulestr(r.get_RFC_rrule(), dtstart=spec_row.start_date.start)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/rrule.py", line 1730, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/dateutil/rrule.py", line 1629, in _parse_rfc
    re.findall('TZID=(?P<name>[^:]+):', s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```
Yep, now I have the task Call mom in Calendar. But only this task, not all the rest.

**Comment by kontheocharis** [comment]
"tomorrow" is not a valid recurrent rule. It has to 1) have some form of repetition, and 2) have an end date. To see what is valid, see https://github.com/kvh/recurrent. Make sure you also add some form of "until [some day]" to your rules, because otherwise notion_scheduler will be running *forever*.

**Comment by sabdemo** [comment]
Great! Excellent! Great big thank you! Now it works. Magic.

Can you please explain me some more questions about n_s itself?

1. Notion_scheduler works only on my computer, right? It doesn't sync anything with github, for example?

2. For some reason I cannot manage to add an exception. I create an event AAA which is on "Mondays until 14 October 2020" and in the field Not on I add "5th October 2020". But this event doesn't appear at all. What am I doing wrong?

**Comment by sabdemo** [comment]
3. Besides only 2 data fields can be created? I tried to add one more, but it doesn't appear. 

4. Imagine I have added 2 events to scheduled database, did `notion_scheduler --log-level=verbose`. How can I add more events or edit the current? I mean, if I create the 3rd event, the first 2 events duplicate themselves in the calendar table after `notion_scheduler --log-level=verbose`. Or I should always delete the events from scheduled database that are already synced with calendar?

**Comment by kontheocharis** [comment]
1. No.
2. "5th October 2020" is not a valid recurrent rule. You have to put valid recurrent rules for this to work.
3. If you add more data fields, you also have to add them in `properties_to_sync` for them to appear.
4. If you use the `tags_property` field correctly, the program should first delete all events in the calendar with Tags = "Scheduled" (or whatever you have set `scheduled_tag` to) and then re-add all of them.

**Comment by sabdemo** [comment]
Great, seems to be, I got everything working now. Thank you!
